#
#   ESAPCIOS API
#

### GET ALL Espacios
GET http://localhost:5000/api/espacios

### GET ID
GET http://localhost:5000/api/espacios/5dbc7d374254b50938efd264


### POST
POST http://localhost:5000/api/espacios
Content-Type: application/json

{
	"descripcion" : "Descripcion de prueba para Espacio",
	"direccion" : "Direccion de prueba para Espacio",
	"parqueadero" : "Parqueadero de priueba àra Espacio",
    "localidad": "Santa Fé",
	"costo" : 26000.00
}


### PATCH
PATCH http://localhost:5000/api/espacios/5dbc7d374254b50938efd264
Content-Type: application/json

{
	"descripcion" : "Descripcion actualizada de Espacio",
	"costo": 74900.00
}

### DELETE
DELETE http://localhost:5000/api/espacios/5dbc7d374254b50938efd264
